# Generated by Django 5.2.5 on 2025-08-20 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "preacher",
                    models.CharField(default="Charles H. Spurgeon", max_length=100),
                ),
                ("content", models.TextField()),
                ("date_preached", models.DateField(default=django.utils.timezone.now)),
                ("scripture_reference", models.CharField(blank=True, max_length=200)),
                (
                    "sermon_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_preached"],
            },
        ),
    ]
