# Generated by Django 5.2.5 on 2025-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sermon",
            old_name="scripture_reference",
            new_name="bible_passage_english",
        ),
        migrations.RenameField(
            model_name="sermon",
            old_name="preacher",
            new_name="preacher_name_english",
        ),
        migrations.RemoveField(
            model_name="sermon",
            name="title",
        ),
        migrations.AddField(
            model_name="sermon",
            name="bible_passage_urdu",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sermon",
            name="preacher_name_urdu",
            field=models.CharField(default="چارلس سپرژن", max_length=100),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_english",
            field=models.CharField(default="Untitled Sermon", max_length=200),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_urdu",
            field=models.CharField(default="Untitled Sermon", max_length=200),
        ),
    ]
